hlxsites/vg-roadchoice-com

- fstab.yaml
updated the mount point to point to the correct sharepoint
> updated mountpoint

- blocks/footer/footer.js
- scripts/scripts.js
Fix #26
Test URLs:
- After: https://26-faq-link--vg-roadchoice-com--hlxsites.hlx.page/
> add target blanck properties

- blocks/find-dealer/find-dealer.css
- blocks/find-dealer/find-dealer.js
- blocks/header/header.js
- scripts/scripts.js
I found 2 small bugs, fixed in this PR:
1. in scripts.js: hero autoblock generates an error if there's no h1 on the page
2. in header.js: if you resize from desktop to mobile the menu will be open
aside from that, the input has 2 events, on Enter pressed and on click on the search button
Fix #4 
Test URLs:
- After: https://4-find-dealer-block--vg-roadchoice-com--hlxsites.hlx.page/
> #4 block up and running & a few fixes

- blocks/carousel/carousel.css
Font is larger at 1200px viewport resolution and beyond
Fix #33
Test URLs:
- After: https://33-carousel-block-fonts--vg-roadchoice-com--hlxsites.hlx.page/
> 33 font size is larger at larger resolutions

- blocks/carousel/carousel.css
- blocks/dealer-locator/dealer-locator.css
- blocks/dealer-locator/dealer-locator.js
also, fix a little esthetic issue with the carousel block
Fix #63 
Test URLs:
- After: https://63-firefox-dl-blank-but-header--vg-roadchoice-com--hlxsites.hlx.page/
> 63 firefox dl blank but header

- blocks/blog-results/blog-results.js
Fix #no-issue
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/
- After: https://fix-title-blog-results--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/
> Blog results title missing

- blocks/header/header.css
- blocks/search/search.css
- blocks/search/search.js
- blocks/search/worker.js
- placeholder.json
- scripts/delayed.js
- scripts/lib-franklin.js
- scripts/scripts.js
This issue also has to update the search results page/block #43
Fix #25
Test URLs:
- After: https://25-duel-search-navigation-bar--vg-roadchoice-com--hlxsites.hlx.page/
> 25 duel search navigation bar

- blocks/iframe/iframe.css
- blocks/iframe/iframe.js
Fix #68 
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/drafts/mvara/forms/forms
- After: https://68-fr-pardot-forms--vg-roadchoice-com--hlxsites.hlx.page/drafts/mvara/forms/forms
> IFrame block to embed external Pardot Forms

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix  #44 
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/cards
- After: https://44-fr-roadchoice--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/cards
> 44 fr roadchoice

- blocks/blog-results/blog-results.js
- blocks/catalogs-table/catalogs-table.css
- blocks/catalogs-table/catalogs-table.js
- blocks/recommendations/recommendations.js
- placeholder.json
- scripts/scripts.js
- styles/sections.css
- styles/styles.css
Fix #45 
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
- After: https://45-catalogs-table-block--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
> 45 catalogs table block

- blocks/breadcrumb/breadcrumb.css
- blocks/carousel/carousel.css
- blocks/catalogs-table/catalogs-table.css
- blocks/catalogs-table/catalogs-table.js
- blocks/filters/filters.css
- blocks/find-dealer/find-dealer.css
- blocks/header/header.css
- blocks/search/search.css
- scripts/scripts.js
- styles/styles.css
Various styling fixes due to some buttons being selected from the scripts file
Catalogs table check for lowercase
also added some general alignements
There are several pages where to check if all changes are working fine
Fix #99
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
- After: https://99-catalogs-links--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
- After: https://99-catalogs-links--vg-roadchoice-com--hlxsites.hlx.page/
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/resources/drafts/shomps/blog/
- After: https://99-catalogs-links--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/
> various fixes

- tools/sidekick/library.html
> Second fix

- tools/sidekick/config.json
> config url changed

- tools/sidekick/config.json
> config json - .page to .live

- tools/sidekick/config.json
- tools/sidekick/library.html
> library new try

- tools/sidekick/config.json
> another one

- blocks/find-dealer/find-dealer.css
Test URLs:
- After: https://FIX-find-dealer-text-color--vg-roadchoice-com--hlxsites.hlx.page/
> Find dealer text color

- blocks/pdp/pdp.js
Fix #77
Test URLs:
- Local images: https://77-pdp-external-images--vg-roadchoice-com--hlxsites.hlx.page/parts?category=batteries&sku=27FCRC
- External Images: https://77-pdp-external-images--vg-roadchoice-com--hlxsites.hlx.page/parts?category=batteries&sku=27CRC
> PDP fix loading of external images

- blocks/pdp/pdp.js
Fixed a few small PDP bugs
- Fixed bug where product attributes were not correctly filtered.
- Format the category name correctly when loading the json file
- Make sure text is properly set on elements
#77
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/parts?category=batteries&sku=27FCRC
- After: https://77-pdp-bugs--vg-roadchoice-com--hlxsites.hlx.page/parts?category=batteries&sku=27FCRC
> PDP Fixed bugs

- tools/sidekick/config.json
- tools/sidekick/library.html
- tools/sidekick/plugins/authors/authors.css
- tools/sidekick/plugins/authors/authors.js
Fix #34 
Test URLs:
- After: https://34-library--vg-roadchoice-com--hlxsites.hlx.page/
> Block Library 

- blocks/cards/cards.css
- blocks/columns/columns.css
- blocks/columns/columns.js
- styles/styles.css
Fix #117
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/part-category/accessories
- After: https://117-columns-block--vg-roadchoice-com--hlxsites.hlx.page/part-category/accessories
also check:
- /brakes
- /cab-and-body
- /chemicals-and-lubricants
- /clutch
- /drivetrain
- /electrical
- /engine
- /engine-cooling
- /hvac
- /lighting
- /steering
- /suspension
- /tools
- /wheel-end
> Category pages and columns blocks

- blocks/filters/filters.js
- blocks/pagination/pagination.css
- blocks/pagination/pagination.js
- blocks/results-list/results-list.css
- blocks/results-list/results-list.js
- blocks/search/search.js
- templates/search-results/search-results.js
if you choose the part number search type and filter by Make filter by the value Others, now bring results.
also, I fixed a bug related to the 1st time is loaded the results page if it comes from the URL itself or if the session Storage is empty
Test Paths:
search/?q=&st=parts&make=others&model=null
search/?q=crc&st=cross&cat=batteries
Fix #107
Test URLs:
- After: https://107-others-filter-has-no-results--vg-roadchoice-com--hlxsites.hlx.page/
> 107 others filter has no results

- blocks/filters/filters.js
- blocks/pdp/pdp.css
- blocks/pdp/pdp.js
Now it gathers all categories that are the same as insensitive cases.
Also, fix a typo in _pdp.js_ and _.css_.
Test-Path:
search/?q=AD642098&st=cross
Fix #110 
Test URLs:
- After: https://110-categories-case-sensitive--vg-roadchoice-com--hlxsites.hlx.page/
> 110 categories case sensitive

- blocks/blog-results/blog-results.js
- blocks/recommendations/recommendations.js
- scripts/scripts.js
- templates/blog-article/blog-article.css
- templates/blog-article/blog-article.js
Fix #123
Test URLs:
- After: https://123-blog-index--vg-roadchoice-com--hlxsites.hlx.page/
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/blog/
- After: https://123-blog-index--vg-roadchoice-com--hlxsites.hlx.page/blog/
> Blog index redirected in all sections to query-index file

- blocks/catalogs-table/catalogs-table.css
- blocks/catalogs-table/catalogs-table.js
Fix #95
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
- After: https://95-pdf-target--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
> add target blanck to pdf catalogs

- blocks/pdp/pdp.css
- placeholder.json
content links updated in /parts document
table text is bold and catalog title text is black
test path:
parts?category=batteries&sku=27FCRC
Fix #121 
Test URLs:
- After: https://121-pdp-links-incorrect--vg-roadchoice-com--hlxsites.hlx.page/
> 121 pdp links incorrect

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix #89
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/cards
- After: https://89-cards-ext-links--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/cards
> Changed cards block to accept external links

- blocks/cookies-table/cookies-table.css
- blocks/cookies-table/cookies-table.js
- styles/styles.css
Its not EXACTLY the same but I think its quite improved 
Fix #144
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/cookies
- After: https://144-cookies-table--vg-roadchoice-com--hlxsites.hlx.page/cookies
> Cookies table block

- blocks/cards/cards.css
Cards 'resources' variation is now singlecolumn in mobile
Fix #90
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/cards
- After: https://90-cards-single-col--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/cards
> cards singleline in mobile

- blocks/manuals-table/manuals-table.css
- blocks/manuals-table/manuals-table.js
- blocks/table/table.css
- blocks/table/table.js
- templates/search-results/search-results.js
I already tested the amount of results and it looks good to me, so I repurposed this branch to fix a little bug in the search results page to not search again if there are already results in session storage.
Also, I add 2 table blocks
manuals-table
table (for warranty page with sticky effect)
Test URLs:
- After: https://107-incorrect-results-in-other--vg-roadchoice-com--hlxsites.hlx.page/
> 107 incorrect results in other

- blocks/catalogs-table/catalogs-table.css
- blocks/category-filters/category-filters.css
- blocks/category-pagination/category-pagination.css
- blocks/category-results-list/category-results-list.css
- blocks/columns/columns.css
- blocks/hero/hero.css
- blocks/pdp/pdp.css
- templates/part-category/part-category.css
- templates/search-results/search-results.css
I cleaned up some CSS files, removing the blanks, and I refactored all the affected files with the CSS nesting and the new media queries selector
Fix #139
Test URLs:
- After: https://139-refactor-css-nesting--vg-roadchoice-com--hlxsites.hlx.page/
> 139 refactor css nesting

- blocks/accordion/accordion.css
- blocks/accordion/accordion.js
- styles/styles.css
Fix #147
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/about/faq
- After: https://147-accordion--vg-roadchoice-com--hlxsites.hlx.page/about/faq
> Accordion block for FAQ

- blocks/accordion/accordion.js
- blocks/breadcrumb/breadcrumb.js
- styles/lazy-styles.css
-Changed the linkedin footer icon 
Also:
-Added the toggle class for accordion block
-Added capitalization on breadcrumb
Fix #29
Test URLs:
- After: https://29-footer-differences--vg-roadchoice-com--hlxsites.hlx.page/
> Linkedin footer icon

- templates/blog-article/blog-article.css
- templates/blog-article/blog-article.js
Category fixes on content and refactored blog template to accept al blocks
Fix #141
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/blog/beat-back-bearings-failure-in-three-easy-steps
- After: https://141-bug-multiple-issues--vg-roadchoice-com--hlxsites.hlx.page/blog/beat-back-bearings-failure-in-three-easy-steps
> Category fixes and blog template refactored

- blocks/category-results-list/category-results-list.js
- blocks/search/search.js
no matter what url is, any search goes to path `/search/? + parameters`
Fix #156 
Test URLs:
- After: https://156-no-search-with-url-params--vg-roadchoice-com--hlxsites.hlx.page/
> #156 search work in any url

- blocks/header/header.css
- blocks/header/header.js
Remove all the level 4 code related in the header block
Fix #42
Test URLs:
- After: https://42-level-4-nav-code-clean-up--vg-roadchoice-com--hlxsites.hlx.page/
> #42 remove all level 4 nav code related

- helix-query.yaml
- helix-sitemap.yaml
- tools/sidekick/config.json
Fix #9 
Test URLs:
- After: https://9-config-index-sitemap--vg-roadchoice-com--hlxsites.hlx.page/
> 9 config index sitemap

- helix-sitemap.yaml
Fix #166 
Test URLs:
- After: https://166-fix-sitemap-url--vg-roadchoice-com--hlxsites.hlx.page/
> Fix to remove `/` from origin url value

- blocks/breadcrumb/breadcrumb.css
- styles/styles.css
Changed the g letter and added styling to breadcrumb
Fix #152
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/blog/make-the-right-battery-match
- After: https://152-cr-special-g--vg-roadchoice-com--hlxsites.hlx.page/blog/make-the-right-battery-match
> done + breadcrumb styling

- blocks/breadcrumb/breadcrumb.css
- blocks/pdp/pdp.css
Proposed solution:
-Less elements in mobile are visible
-Horizontal scrolling in small views overflow
Paths:
-/parts?category=batteries&sku=24CRC
-/blog/steer-clear-of-no-start-situations-with-road-choice-batteries
Fix #167
Test URLs:
- After: https://167-bug-breadcrumb-pdp--vg-roadchoice-com--hlxsites.hlx.page/
> Breadcrumb horizontal scrolling for block and pdp

- blocks/catalogs-table/catalogs-table.js
Fix #183
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs
- After: https://183-sort-catalogs--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs
> Sorting added by letter in catalogs block

- styles/favicon.svg
Fix #185
Test URLs:
- After: https://185-modify-favicon--vg-roadchoice-com--hlxsites.hlx.page/
> Favicon changed

- blocks/search/search.js
Path: search/?q=WBS18B&st=cross
Fix #187
Test URLs:
- After: https://187-cr-search-oem--vg-roadchoice-com--hlxsites.hlx.page/
> Changed CR search params to only point OEM_NUM

- blocks/results-list/results-list.js
test path: 
Fix #189
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/search/?q=&st=parts&make=ford&model=a9513&cat=charge+air+coolers
- After: https://189-category-filters--vg-roadchoice-com--hlxsites.hlx.page/search/?q=&st=parts&make=ford&model=a9513&cat=charge+air+coolers
> check for category in search

- scripts/delayed.js
Fix #58 
Test URLs:
- After: https://58-artibot-script--vg-roadchoice-com--hlxsites.hlx.page/
> Fix Artibot cookie consent check

- scripts/delayed.js
Fix #58 
Test URLs:
- After: https://58-artibot-script--vg-roadchoice-com--hlxsites.hlx.page/
> Fix to remove the artibot embed settings tag

- blocks/category-filters/category-filters.js
- blocks/category-results-list/category-results-list.js
- scripts/scripts.js
- templates/part-category/part-category.js
Changed the storing of the products to window element due to lack of space in sessionStorage (see screenshot)
Added "Accept-Encodign": "gzip" to the fetch headers.
Fix #204
Test URLs:
- After: https://204-bug-bumper-filters--vg-roadchoice-com--hlxsites.hlx.page/
> Changed sessionStorage for window and added Accept-Encoding to fetch calls

- scripts/lib-franklin.js
Fix #202
Test URLs:
- After: https://202-bug-detail-images--vg-roadchoice-com--hlxsites.hlx.page/
> Modify pathname for small images

- blocks/category-pagination/category-pagination.js
For subtask in issue 207
Test URLs:
- After: https://207-show-more--vg-roadchoice-com--hlxsites.hlx.page/
> Paginattion added to sub-category pages

- blocks/category-filters/category-filters.js
- templates/part-category/part-category.js
Fix task 2 of issue n° 207
Test URLs:
- After: https://211-breadcrumb-fixes--vg-roadchoice-com--hlxsites.hlx.page/
> breadcrumb fix

- blocks/results-list/results-list.js
- blocks/search/search.js
- templates/search-results/search-results.css
fix 1: Search for "11-312" now shows only 2 results
fix 2: large results now are correctly aligned
fix 3: Search for ‘ABP ‘ or  ‘ABP‘ now share the same amount of results
all these fixes are to fix the issue [491](https://github.com/hlxsites/vg-macktrucks-com/issues/491)
Fix #187 
Test URLs:
- After: https://187-search-edge-cases-issues--vg-roadchoice-com--hlxsites.hlx.page/
> 187 search edge cases issues

- blocks/breadcrumb/breadcrumb.js
- blocks/pdp/pdp.css
- blocks/pdp/pdp.js
- templates/part-category/part-category.js
any URL that doesn't end with "/" it doesn't generate a wrong breadcrumb
Fix an item from issue 207
Test URLs:
- After: https://207-breadcrumb-404-last-item--vg-roadchoice-com--hlxsites.hlx.page/
> 207 breadcrumb last item has a correct link

- scripts/delayed.js
- scripts/scripts.js
- styles/styles.css
Added a fuctionality to create button with props to be added and assigned the preference center togglo to `id=preference`
Fix part 3 of issue 207
Test URLs:
- After: https://FIX-cookie-preference-btn--vg-roadchoice-com--hlxsites.hlx.page/
> Added btn functionality and cookie preference center

- blocks/results-list/results-list.js
- blocks/search/search.js
added another filter to check if there are already shown the same Part Number to show only the first one when you search by Part Number
- if you search by " " (blank space), then now show a no-results page
- if the results array is empty, then the loading element is always removed, even if the data from the worker is not loaded yet for a weird misalign with the custom events and the worker message event itself
#
Fix #214 
Test URLs:
- After: https://214-duplicate-pn-search-results--vg-roadchoice-com--hlxsites.hlx.page/
> 214 duplicate pn search results

- blocks/dealer-locator/dealer-locator.css
/where-to-buy
Fix #217
Test URLs:
- After: https://217-google-logo--vg-roadchoice-com--hlxsites.hlx.page/
> Make google logo appear

- blocks/v2-embed/v2-embed.css
- blocks/v2-embed/v2-embed.js
- scripts/video-helper.js
Fix #237
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.aem.page/drafts/alan/v2-embed-multiple-config
- After: https://237-aem-assets-hosted-videos--vg-roadchoice-com--hlxsites.aem.page/drafts/alan/v2-embed-multiple-config
> AEM Assets hosted videos #237

- head.html
- scripts/common.js
Fix #268
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.aem.page/
- After: https://268-multi-lang-config--vg-roadchoice-com--hlxsites.aem.page/
> Multi language configuration #268

- blocks/hero/hero.css
- blocks/hero/hero.js
Fix #262
Also added variants for left, right and black text (not in the issue)
Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.aem.page/drafts/shomps/hero
- After: https://262-hero-block--vg-roadchoice-com--hlxsites.aem.page/drafts/shomps/hero
> Hero block #262
